// navbar
export const SET_CONNECT_WALLET = 'SET_CONNECT_WALLET'
export const SET_DISCONNECT_WALLET = 'SET_DISCONNECT_WALLET'
export const SET_USERADDRESS = 'SET_USERADDRESS'
export const SET_SHOW_STATS = 'SET_SHOW_STATS'
export const SET_IS_AUTOMATION = 'SET_IS_AUTOMATION'
export const SET_IS_CONNECTOR_ID = 'SET_IS_CONNECTOR_ID'
export const SET_IS_SYNCED_WITH_API = 'SET_IS_SYNCED_WITH_API'

// notification
export const ERROR = 'ERROR'
export const SUCCESS = 'SUCCESS'
export const START_LOADER = 'START_LOADER'
export const STOP_LOADER = 'STOP_LOADER'
export const TX_HASH = 'TX_HASH'
